name: CI

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git track origin/main

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm


      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint:ci

      - name: Run tests
        run: pnpm test
