name: Release
on:
  push:
    branches: 
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Please
    permissions:
      contents: write
      pull-requests: write
    
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag: ${{ steps.release-please.outputs.tag }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please

  publish:
    needs: release
    name: Publish to NPM ${{ needs.release.outputs.tag }}
    if: needs.release.outputs.release_created == 'true'
    environment: NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - name: Install
        run: |
          pnpm install

      - name: Publish
        run: |
          pnpm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          pnpm publish --access public




    

